version: '2'

services:
  p2p-chat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p2p-chat-server
    ports:
      - "127.0.0.1:17890:17890"
    restart: always
    environment:
      - FLASK_ENV=production