version: '2'

services:
  p2p-chat:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: p2p-chat-server
    ports:
      - "7890:7890"
    restart: always
    environment:
      - FLASK_ENV=production
